require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/RedundantBegin:
  Enabled: false
